//
//  CurrencyUtils.swift
//  Finance Tracker app
//
//  Created by Jackson Mugo on 29/08/2025.
//


import Foundation

struct CurrencyUtils {
    
    
    // Helper method to get country name from currency code
    static func getCountryName(for currency: String) -> String {
        switch currency {
        case "EUR": return "Eurozone"
        case "GBP": return "United Kingdom"
        case "JPY": return "Japan"
        case "AUD": return "Australia"
        case "CAD": return "Canada"
        case "CHF": return "Switzerland"
        case "CNY": return "China"
        case "INR": return "India"
        case "NZD": return "New Zealand"
        case "SGD": return "Singapore"
        case "ZAR": return "South Africa"
        case "AED": return "United Arab Emirates"
        case "SAR": return "Saudi Arabia"
        case "EGP": return "Egypt"
        case "NGN": return "Nigeria"
        case "RUB": return "Russia"
        case "TRY": return "Turkey"
        case "BRL": return "Brazil"
        case "MXN": return "Mexico"
        case "AFN": return "Afghanistan"
        case "ALL": return "Albania"
        case "DZD": return "Algeria"
        case "AOA": return "Angola"
        case "ARS": return "Argentina"
        case "AMD": return "Armenia"
        case "AWG": return "Aruba"
        case "AZN": return "Azerbaijan"
        case "BAM": return "Bosnia and Herzegovina"
        case "BBD": return "Barbados"
        case "BDT": return "Bangladesh"
        case "BGN": return "Bulgaria"
        case "BHD": return "Bahrain"
        case "BIF": return "Burundi"
        case "BMD": return "Bermuda"
        case "BND": return "Brunei"
        case "BOB": return "Bolivia"
        case "BOV": return "Bolivian Mvdol"
        case "BSD": return "Bahamas"
        case "BTN": return "Bhutan"
        case "BWP": return "Botswana"
        case "BYN": return "Belarus"
        case "BZD": return "Belize"
        case "CDF": return "Democratic Republic of the Congo"
        case "CLP": return "Chile"
        case "COP": return "Colombia"
        case "CRC": return "Costa Rica"
        case "CUP": return "Cuba"
        case "CVE": return "Cape Verde"
        case "CZK": return "Czech Republic"
        case "DJF": return "Djibouti"
        case "DKK": return "Denmark"
        case "DOP": return "Dominican Republic"
        case "ERN": return "Eritrea"
        case "ESP": return "Spain"
        case "ETB": return "Ethiopia"
        case "FJD": return "Fiji"
        case "FKP": return "Falkland Islands"
        case "FOK": return "Faroe Islands"
        case "GEL": return "Georgia"
        case "GHS": return "Ghana"
        case "GIP": return "Gibraltar"
        case "GMD": return "Gambia"
        case "GNF": return "Guinea"
        case "GRC": return "Greece"
        case "GRD": return "Grenada"
        case "GTQ": return "Guatemala"
        case "GUF": return "French Guiana"
        case "GUM": return "Guam"
        case "GUY": return "Guyana"
        case "HKD": return "Hong Kong"
        case "HNL": return "Honduras"
        case "HRK": return "Croatia"
        case "HTG": return "Haiti"
        case "HUF": return "Hungary"
        case "IDR": return "Indonesia"
        case "ILS": return "Israel"
        case "IQD": return "Iraq"
        case "IRR": return "Iran"
        case "ISK": return "Iceland"
        case "JMD": return "Jamaica"
        case "JOD": return "Jordan"
        case "KES": return "Kenya"
        case "KGS": return "Kyrgyzstan"
        case "KHR": return "Cambodia"
        case "KMF": return "Comoros"
        case "KPW": return "North Korea"
        case "KRW": return "South Korea"
        case "KWD": return "Kuwait"
        case "KYD": return "Cayman Islands"
        case "KZT": return "Kazakhstan"
        case "LAK": return "Laos"
        case "LBP": return "Lebanon"
        case "LKR": return "Sri Lanka"
        case "LRD": return "Liberia"
        case "LSL": return "Lesotho"
        case "LTL": return "Lithuania"
        case "LUX": return "Luxembourg"
        case "LVL": return "Latvia"
        case "LYD": return "Libya"
        case "MAD": return "Morocco"
        case "MDL": return "Moldova"
        case "MGA": return "Madagascar"
        case "MKD": return "North Macedonia"
        case "MMK": return "Myanmar"
        case "MNT": return "Mongolia"
        case "MOP": return "Macau"
        case "MRO": return "Mauritania"
        case "MRU": return "Mauritania"
        case "MUR": return "Mauritius"
        case "MWK": return "Malawi"
        case "MYR": return "Malaysia"
        case "MZN": return "Mozambique"
        case "NAD": return "Namibia"
        case "NGA": return "Nigeria"
        case "NIO": return "Nicaragua"
        case "NPR": return "Nepal"
        case "OMR": return "Oman"
        case "PAB": return "Panama"
        case "PEN": return "Peru"
        case "PGK": return "Papua New Guinea"
        case "PHP": return "Philippines"
        case "PKR": return "Pakistan"
        case "PLN": return "Poland"
        case "PYG": return "Paraguay"
        case "QAR": return "Qatar"
        case "RON": return "Romania"
        case "RSD": return "Serbia"
        case "RWF": return "Rwanda"
        case "SBD": return "Solomon Islands"
        case "SCR": return "Seychelles"
        case "SDG": return "Sudan"
        case "SEK": return "Sweden"
        case "SHP": return "Saint Helena"
        case "SLL": return "Sierra Leone"
        case "SOS": return "Somalia"
        case "SPL": return "Saint Pierre and Miquelon"
        case "SRD": return "Suriname"
        case "SSP": return "South Sudan"
        case "STN": return "São Tomé and Príncipe"
        case "SYP": return "Syria"
        case "SZL": return "Eswatini"
        case "THB": return "Thailand"
        case "TJS": return "Tajikistan"
        case "TMT": return "Turkmenistan"
        case "TND": return "Tunisia"
        case "TOP": return "Tonga"
        case "TTD": return "Trinidad and Tobago"
        case "TVD": return "Tuvalu"
        case "TWD": return "Taiwan"
        case "TZS": return "Tanzania"
        case "UAH": return "Ukraine"
        case "UGX": return "Uganda"
        case "USD": return "United States"
        case "UYU": return "Uruguay"
        case "UZS": return "Uzbekistan"
        case "VEF": return "Venezuela"
        case "VND": return "Vietnam"
        case "VUV": return "Vanuatu"
        case "WST": return "Samoa"
        case "XAF": return "Central African CFA franc"
        case "XCD": return "East Caribbean dollar"
        case "XOF": return "West African CFA franc"
        case "YER": return "Yemen"
        case "ZMW": return "Zambia"
        case "ZWL": return "Zimbabwe"
        default: return currency
        }
    }
    
    
    
    static func getCurrencyName(for currency: String) -> String {
        switch currency {
        case "AED": return "Dirham"
        case "AFN": return "Afghani"
        case "ALL": return "Lek"
        case "AMD": return "Dram"
        case "ANG": return "Guilder"
        case "AOA": return "Kwanza"
        case "ARS": return "Peso"
        case "AUD": return "Dollar"
        case "AWG": return "Florin"
        case "AZN": return "Manat"
        case "BAM": return "Convertible Mark"
        case "BBD": return "Dollar"
        case "BDT": return "Taka"
        case "BGN": return "Lev"
        case "BHD": return "Dinar"
        case "BIF": return "Franc"
        case "BMD": return "Dollar"
        case "BND": return "Dollar"
        case "BOB": return "Boliviano"
        case "BRL": return "Real"
        case "BSD": return "Dollar"
        case "BTN": return "Ngultrum"
        case "BWP": return "Pula"
        case "BYN": return "Ruble"
        case "BZD": return "Dollar"
        case "CAD": return "Dollar"
        case "CDF": return "Franc"
        case "CHF": return "Franc"
        case "CLP": return "Peso"
        case "CNY": return "Yuan"
        case "COP": return "Peso"
        case "CRC": return "Colón"
        case "CUP": return "Peso"
        case "CVE": return "Escudo"
        case "CZK": return "Koruna"
        case "DJF": return "Franc"
        case "DKK": return "Krone"
        case "DOP": return "Peso"
        case "DZD": return "Dinar"
        case "EGP": return "Pound"
        case "ERN": return "Nakfa"
        case "ETB": return "Birr"
        case "EUR": return "Euro"
        case "FJD": return "Dollar"
        case "FKP": return "Pound"
        case "GBP": return "Pound Sterling"
        case "GEL": return "Lari"
        case "GHS": return "Cedi"
        case "GIP": return "Pound"
        case "GMD": return "Dalasi"
        case "GNF": return "Franc"
        case "GTQ": return "Quetzal"
        case "GYD": return "Dollar"
        case "HKD": return "Dollar"
        case "HNL": return "Lempira"
        case "HRK": return "Kuna"
        case "HTG": return "Gourde"
        case "HUF": return "Forint"
        case "IDR": return "Rupiah"
        case "ILS": return "Shekel"
        case "INR": return "Rupee"
        case "IQD": return "Dinar"
        case "IRR": return "Rial"
        case "ISK": return "Krona"
        case "JMD": return "Dollar"
        case "JOD": return "Dinar"
        case "JPY": return "Yen"
        case "KES": return "Shilling"
        case "KGS": return "Som"
        case "KHR": return "Riel"
        case "KMF": return "Franc"
        case "KPW": return "Won"
        case "KRW": return "Won"
        case "KWD": return "Dinar"
        case "KYD": return "Dollar"
        case "KZT": return "Tenge"
        case "LAK": return "Kip"
        case "LBP": return "Pound"
        case "LKR": return "Rupee"
        case "LRD": return "Dollar"
        case "LSL": return "Loti"
        case "LYD": return "Dinar"
        case "MAD": return "Dirham"
        case "MDL": return "Leu"
        case "MGA": return "Ariary"
        case "MKD": return "Denar"
        case "MMK": return "Kyat"
        case "MNT": return "Tugrik"
        case "MOP": return "Pataca"
        case "MRU": return "Ouguiya"
        case "MUR": return "Rupee"
        case "MVR": return "Rufiyaa"
        case "MWK": return "Kwacha"
        case "MXN": return "Peso"
        case "MYR": return "Ringgit"
        case "MZN": return "Metical"
        case "NAD": return "Dollar"
        case "NGN": return "Naira"
        case "NIO": return "Cordoba"
        case "NOK": return "Krone"
        case "NPR": return "Rupee"
        case "NZD": return "Dollar"
        case "OMR": return "Rial"
        case "PAB": return "Balboa"
        case "PEN": return "Sol"
        case "PGK": return "Kina"
        case "PHP": return "Peso"
        case "PKR": return "Rupee"
        case "PLN": return "Zloty"
        case "PYG": return "Guarani"
        case "QAR": return "Rial"
        case "RON": return "Leu"
        case "RSD": return "Dinar"
        case "RUB": return "Ruble"
        case "RWF": return "Franc"
        case "SAR": return "Riyal"
        case "SBD": return "Dollar"
        case "SCR": return "Rupee"
        case "SDG": return "Pound"
        case "SEK": return "Krona"
        case "SGD": return "Dollar"
        case "SHP": return "Pound"
        case "SLL": return "Leone"
        case "SOS": return "Shilling"
        case "SRD": return "Dollar"
        case "STN": return "Dobra"
        case "SYP": return "Pound"
        case "SZL": return "Lilangeni"
        case "THB": return "Baht"
        case "TJS": return "Somoni"
        case "TMT": return "Manat"
        case "TND": return "Dinar"
        case "TOP": return "Paʻanga"
        case "TRY": return "Lira"
        case "TTD": return "Dollar"
        case "TVD": return "Dollar"
        case "TWD": return "Dollar"
        case "TZS": return "Shilling"
        case "UAH": return "Hryvnia"
        case "UGX": return "Shilling"
        case "USD": return "Dollar"
        case "UYU": return "Peso"
        case "UZS": return "Som"
        case "VES": return "Bolívar"
        case "VND": return "Dong"
        case "VUV": return "Vatu"
        case "WST": return "Tala"
        case "XAF": return "CFA Franc BEAC"
        case "XCD": return "Dollar"
        case "XOF": return "CFA Franc BCEAO"
        case "XPF": return "CFP Franc"
        case "YER": return "Rial"
        case "ZAR": return "Rand"
        case "ZMW": return "Kwacha"
        case "ZWL": return "Dollar"
        default: return currency
        }
    }
}
